development:
  adapter: postgresql
  encoding: unicode
  database: linkstack_development
  pool: 5
  username: David
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: linkstack_test
  pool: 5
  username: David
  password:
